### PR TITLE
add Ubuntu 22.04 build support

### PR DESCRIPTION
**Pull request by razr**
added support to build the Ubuntu 22.04 kernel for RPI4
- updated README and Dockerfile description
- added extra parameters to the `build-latest` workflow: `ubuntu_version` and `kernel_version`
- added extra parameters to the `build-stable` workflow: `ubuntu_version` and `kernel_version`
The workflow can be started manually, see below for the parameters example, they are the same as for the Dockerfile

Here is a docker command to build the 22.04 kernel image.
```bash
docker build --build-arg UBUNTU_VERSION=jammy --build-arg KERNEL_VERSION=5.15.0 --build-arg LTTNG_VERSION=2.13 -t rtwg-image-22.04 .
```

It turned out that `VIRTUALIZATION` is not supported (`PREEMPT_RT` item is not shown in the menu) by the 5.15 real-time kernel, For that reason, it is disabled in the [.config-fragment](https://github.com/ros-realtime/linux-real-time-kernel-builder/blob/master/.config-fragment)

### CODE REVIEW

**Review by shuhaowu — APPROVED** [review]
Nice! Once this work is merged, I can get started porting the image builder to humble + jammy.

**Review by LanderU — COMMENTED** [review]
is this ready for being reviewed?

**Comment by shuhaowu** [comment]
Any update on this? It would be nice to unblock the rpi4 image work so we can release a humble + jammy image soonish.

**Review by LanderU — APPROVED** [review]
LGTM!

**Pull request merged**
